name: Build macOS Application

on: 
  workflow_dispatch:

jobs:
  build:
    name: Build for macOS
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.2'
    - name: Install Dependencies
      run: pip install pyinstaller
    - name: Compress Application for Distribution
      run: zip -r SelExtCopyUtil.zip dist/SelExtCopyUtil.app
    - name: Upload Application
      uses: actions/upload-artifact@v2
      with:
        name: macOS-Application
        path: SelExtCopyUtil.zip
